=== AysaAlizadeh/hamshahri-ir/Dataset/hamshahri.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT HAMSHAHRI2 (COPYRIGHT, DOC+)>
<!ELEMENT DOC (DOCID, DOCNO, ORIGINALFILE, ISSUE, DATE, CAT, CAT, TITLE, TEXT)>
<!ELEMENT DOCID (#PCDATA)>
<!ELEMENT DOCNO (#PCDATA)>
<!ELEMENT ORIGINALFILE (#PCDATA)>
<!ELEMENT ISSUE (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ATTLIST DATE calender (Persian | Western) #REQUIRED>
<!ELEMENT CAT (#PCDATA)>
<!ATTLIST CAT xml:lang (en | fa) #REQUIRED>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT TEXT (#PCDATA)>

=== AysaAlizadeh/hamshahri-ir/Dataset/HAM2-020129.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE HAMSHAHRI2 SYSTEM "hamshahri.dtd">

<HAMSHAHRI2>
<COPYRIGHT>
<![CDATA[Hamshahri2 Corpus, Beta Release!
Copyright 2004-2008, Database Research Group (DBRG), Faculty of Engineering, University of Tehran
All the news content in the corpus is copyrighted by Hamshahri Newspaper (www.hamshahri.net)

Homepage:
http://ece.ut.ac.ir/dbrg/hamshahri/ham2

Contact:
darrudi@insf.org 

Please view the enclosed `Help.txt` file in the package for more information (tag description, etc).

IT IS A BETA RELEASE, PLEASE DON NOT REDISTRIBUTE IT!]]>
</COPYRIGHT>
<DOC>
<DOCID>HAM2-801109-001</DOCID>
<DOCNO>HAM2-801109-001</DOCNO>
<ORIGINALFILE>/1380/801109/adabh.htm</ORIGINALFILE>
<ISSUE>29 jan 2002 سه شنبه 9بهمن 1380،، شماره 2635</ISSUE>
<DATE calender="Western">2002-01-29</DATE>
<DATE calender="Persian">1380/11/09</DATE>
<CAT xml:lang="fa">ادب و هنر</CAT>
<CAT xml:lang="en">Literature and Art</CAT>
<TITLE>
<![CDATA[هماهنگي آهنگساز و شاعر]]>
</TITLE>
<TEXT>
<IMAGE>/1380/801109/p14-1.jpg</IMAGE>
<![CDATA[
گفت وگو با استاد همايون خرم، آهنگساز پيشكسوت موسيقي 
ايراني
اشاره: 
چندي پيش گفت و گويي از استاد همايون خرم چاپ كرديم كه 
مورد استقبال و توجه خوانندگان همشهري قرار گرفت. اكنون 
و بار ديگر در صفحه موسيقي با استاد همايون خرم گفت و گو
كرده ايم و نكاتي ديگر از زندگي و سابقه هنري وي را
مورد بررسي قرار داده ايم. با هم 
مي خوانيم: 
* شما آهنگ هاي زيادي ساختيد، آيا خاطرتان هست اولين 
آهنگي كه ساختيد چه نام داشت؟
- اولين آهنگي كه ساختم، شايد هيچ گاه در راديو اجرا نشد. 
سال سوم دبيرستان بودم و جشني در مدرسه مي گرفتند، 
مدرسه اي كه من مي رفتم علميه نام داشت كه تا سال پنجم 
متوسطه آنجا تحصيل كردم و سال ششم متوسطه را در كالج 
البرز در رشته رياضي ادامه دادم، عرض كردم كه در مدرسه 
علميه جشني گرفته بودند و من هم چون با موسيقي آشنايي 
داشتم آهنگي ساختم در اصفهان، كه شعرش را هم يكي از
محصلين همانجا گفت و يكي از خواننده هاي همان مدرسه هم 
اين شعر را با آهنگي كه ساخته بودم خواند، ولي متاسفانه 
هيچ وقت اجرا نشد و هميشه هم فكر مي كنم كه چرا آن را
اجرا نكردم. اما اولين كاري كه در راديو اجرا كردم، تصور
مي كنم آهنگي بود كه در مقام دشتي ساخته بودم و در آن از
آهنگ زرد مليجه ساخته استاد صبا استفاده كرده بودم و
مي دانيد كه اين آهنگ يادگار گيلان است زماني كه استاد
صبا رياست هنرستان آنجا را به عهده داشتند و به جاهاي 
مختلف گيلان مي رفتند. 
* در مورد شيوه كارتان مي خواستيم بيشتر توضيح بدهيد، 
اين كه چگونه آهنگ مي ساختيد و رابطه تان با شعر چطور
بود، آيا ابتدا شعر را انتخاب مي كرديد و براساسش آهنگ 
مي ساختيد يا اين كه آهنگ ساخته مي شد و بعد شعر انتخاب
مي شد و يا مثلا آهنگ را براي خواننده خاصي مي نوشتيد؟
- من هميشه سعي مي كردم وقتي كه براي خواننده خاصي آهنگ 
مي سازم، نخست مشخصات ويژه صداي او را درنظر داشته باشم 
و يا اين كه آهنگي كه مي سازم با صداي كدام خواننده 
هماهنگي بيشتري دارد و باز هم با نهايت تواضع عرض مي كنم 
كه هر آهنگي كه براي هر خواننده اي ساختم مطرح شد و مورد
استقبال مردم قرار گرفت. به خاطر اين كه دقت مي كردم اين 
خواننده توانايي كامل اجراي آهنگ را داشته باشد و البته 
اين تنها يكي از فاكتورها بود و نكات فني زيادي رعايت 
مي شد. در مورد نوع آهنگسازي بايد بگويم كه به دو صورت 
انجام مي شد يكي اينكه آهنگسازابتدا آهنگي را مي ساخت 
و بعد با شاعر تماس گرفته مي شدواين تماس به صورت 
درستي انجام مي شد كه شاعر درك صحيحي از آهنگساز و آهنگ 
ساخته شده داشته باشد و من به اين مورد خيلي حساس بودم 
كه شاعر درك كاملي از ملودي ها پيدا كند و بتواند آن را
به صورت كلام عرضه كند و به همين گو نه وقتي با شاعرهاي 
عزيز كار مي كردم مثلا مي گفتم شعر شما خوب است اما
متاسفانه با ملودي ها هماهنگي لازم را ندارد و بايد
تغيير كند، يا اين منظوري كه شما داريد روي آن كار
مي كنيد مبين آهنگ ساخته شده نيست مثلا اين آهنگ حكايت 
از هجري دارد ودر اين صورت صحبت از وصل جايز نيست، 
همان طوري كه گفتم من راجع به اين موضوع خيلي حساسيت 
داشتم چون كه خودم مطالعات زيادي درباره ادبيات داشتم و
اعتقاد دارم كه اگر موسيقيداني با ادبيات خود بيگانه 
باشد و يا ادبيات را به اندازه كافي نداند در كارش هم 
متاسفانه بايد شك كرد. به خاطر اينكه ادبيات ما با
موسيقي ما ارتباط تنگاتنگي دارد اين بود كه وقتي احساس 
مي كردم شعر و كلام مبين آهنگ و ملودي نيست با شاعران 
عزيز مشورت مي كردم كه حتما اصلاحات واقعي صورت گيرد و
بارها اين قضيه اتفاق افتاد و البته در بيشتر مواقع 
دوستان شاعر مسئله را درك مي كردند و كار به خوبي انجام 
مي گرفت و اصولا تا هماهنگي لازم بين شعر و موسيقي صورت 
نمي گرفت من راضي نمي شدم كه كار تمام شده تلقي شود. اين 
يك نوع آهنگسازي بود و نوع ديگر ساختن آهنگ بر روي شعر
شاعر بود كه آن البته ازكارهاي بسيار مشكل است و در
اينجا آهنگساز است كه بايد درك كند كه براي اين شعر چه 
مقامي خوب است يا براي اين كلمات چه حركتهايي بايد در
ملودي انجام شود و اين كار در حقيقت هم اطلاعات نظري خوب
مي خواهد و هم شناخت كاملي از موسيقي ايراني. بايستي كه 
بنيه اين موسيقي را درك كرد و هم اينكه ذوق و خلاقيت 
بايد باشد كه آن ديگر خدادادي است و من يك نمونه اي را
براي شما عرض كنم آن هم در مورد جناب ابوالحسن ورزي كه 
قبلا صحبتش شد، شبي ما منزل ايشان بوديم و ايشان يك 
غزلي براي من خواندند و گفتند كه دلم مي خواهد همايون 
روي اين غزل آهنگي بسازد، غزل مطلعش اين بود: 
آمد اما در نگاهش آن نوازشها نبود
چشم خواب آلوده اش را مستي رويا نبود
نقش عشق و آرزو از چهره دل شسته بود
عكس شيدايي در آن آئينه سيما نبود
و الي آخر، كه البته يك ترجيع هم داشت. من خيلي از شعر
خوشم آمد، گفتم شعر واقعا زيبايي است و من حتما بر روي 
آن آهنگي خواهم ساخت. رفتم منزل و بايد بگويم كه در طي 
دو ماه هر چي مي ساختم پاره مي كردم، چون چيزي كه 
مي خواستم نمي شد. البته اگر مي خواستم روي اين افاعيل 
آهنگ بسازم مثل: فاعلاتن فاعلاتن فاعلاتن فاعلات، يك چيز
سرهم بندي شده ضربي كم ارزش از آب درمي آمد كه 
به هيچ وجه مرا راضي نمي ساخت و اگر به اين مي خواستم 
بسنده كنم البته فورا ساخته مي شد، ولي با آن وسواسي كه 
عرض كردم بنده نسبت به كارها داشتم، راضي ام نمي كرد. دو
ماه كار كردم هيچي نشد. يك شب خوابيده بودم حدودا ساعت 
چهار صبح بود. من تازه هم ازدواج كرده بودم و دخترم شش 
ماهه بود. عرض كنم كه روي كمد پا تختي، همسر من يك كاغذ
نت سفيد و يك خودكار گذاشته بود. ساعت درست چهار صبح بود
كه يك مرتبه ديدم انگار باران نت مي بارد و من اسم اين 
باران را گذاشتم باران رحمت، از خواب پريدم و اين باران 
نت همينطور مي باريد و من بلافاصله شروع كردم به نوشتن و
تمام تلفيق شعر و موسيقي درست بود، جوابهاي اركستر نوشته 
شد، حتي مقدمه اركستر هم نوشته شد و جالب كه تمام افاعيل 
شكسته شده بود و آن افاعيل اوليه ديگر نبود و به صورت 
اخطار دو- سه مرتبه مي گفت آمد، آمد، آمد اما در نگاهش... 
و اصلا چيز جديدي بود و به صورت كامل هم نوشته شد و دو
روز بعد اركستره اش كردم، يعني براي اركستر نوشتم و با
خواننده كار كردم كه در زمان خودش استقبال عجيبي از اين 
آهنگ شد و هنوز هم دوستان خاطره ها دارند و جوانها هم كه 
حالا اين نوارها را گوش مي كنند به اين آهنگ اشاره دارند
و جالب اينجاست كه آقاي ورزي به من گفتند همايون جان اين 
شعر مرا تنها عده اي از خواص شعر و ادب مي شناختند، ولي 
تو كاري كردي كه تمام مردم ايران فهميدند من چنين شعري 
سروده ام كلا مي خواستم عرض كنم كه ساختن آهنگ براي 
شعر كار چندان آساني نيست، الان ما مي بينيم همينطور
مرتب روي شعرهاي حافظ آهنگ درست مي كنند، من فكرمي كنم 
در بعضي موارد حافظ هم روحش راضي نباشد از اينكه اين 
شعرهاي با اين عظمت عرفاني و با اين پيام هاي عارفانه به 
همين سادگي مورد استفاده قرار بگيرند و احساس مسئوليتي 
نباشد. البته بنده شش آهنگ هم بر روي اشعار حافظ ساختم 
كه پيش از انقلاب بود و آن آهنگ ها را آقاي گلچين اجرا
كرده بودند به نام شاخه نبات و يكي از آنها" يوسف گمگشته 
بازآيد به كنعان غم مخور" بود و ديگري "مرا مهر سيه 
چشمان زسر بيرون نخواهد شد" و بازهم "گلعذاري زگلستان 
جهان ما را بس "، كه همه اينها با دقت و وسواس تمام 
آهنگسازي مي شد. 
* شعر كلاسيك ايران به جاي خود، در اينجا مي خواستيم كه 
راجع به ترانه سرايي در ايران صحبت كنيد، چون ما
ترانه سراهاي بسيار قوي و خلاقي داشتيم كه موسيقي ايران 
مديون آنان است، در اين زمينه براي ما بگوييد؟
- بنده از ترانه سراها خاطرات بسيار خوبي دارم و همانطور
كه گفتيد اينها بسيار انسانهاي برجسته اي بودند مثل 
آقايان معيني كرمانشاهي، بيژن ترقي، تورج نگهبان، 
شادروان كريم فكور، نواب صفا، بهادر يگانه و همينطور
خانم سيمين بهبهاني و آقاي نظام فاطمي. 
* ترانه ماندگار و ارزشمند" تو اي پري كجايي "از چه كسي 
بود؟
- خوب شد يادآوري كرديد، شعر اين ترانه از دوست بسيار
خوبم، آقاي هوشنگ ابتهاج است و ايشان غزلسراي بسيار
بزرگي هستند و در عين حال انسان خيلي با احساسي هستند و
در آن ايام مسئول موسيقي راديو بودند و از من خواستند كه 
آهنگي بسازم و ايشان شعرش را بسرايند كه من هم آهنگ 
" تواي پري كجايي "را ساختم كه در واقع يك الهام خدايي 
بود و آقاي ابتهاج هم براساس موسيقي ساخته شده شعر را
آماده كردند و البته با هماهنگي و با تبادل افكار يكديگر
كار ساختن ترانه پيش رفت و تمامي آن حساسيت هاكه گفتم 
رعايت شد و خوشبختانه اين كار از هر نظر كامل از آب
درآمد البته كار ديگري با آقاي ابتهاج داريم كه 
متاسفانه همين طوري مانده و ايشان هر وقت مرا مي بينند
سراغش را مي گيرند و كار بسيار قشنگي است كه اميدوارم در
فرصت مناسب كاملش كنم. 
* در مورد ترانه بسيار مشهور" امشب در سر شوري دارم "كه 
از زيباترين و خاطره انگيزترين ترانه هاي ايران محسوب
مي شود چه صحبتهايي داريد؟
- حقيقت اين كه خانم پروين كارمند يك اداره بودند و من 
هم آشنايي با ايشان نداشتم، منتها هنرمند با ارزش سينما
و تئاتر خانم توران مهرزاد يك روز به من زنگ زدند و
گفتند كه مي خواهم يك نفر را به شما معرفي كنم كه علاقه 
بسيار زيادي به موسيقي دارد و از نظر معنوي هم خانم 
بسيار فهميده اي هستند. من صداي خانم پروين را شنيدم و
گفتم كه ايشان بايد فقط در محدوده راديو فعاليت داشته 
باشند چون واهمه داشتم كه فعاليتهاي بيروني خواننده را
از مسير واقعي موسيقي منحرف كند و آن كارهاي اصيلي را كه 
مي تواند انجام بدهد ناخودآگاه به سوي اجراي آثار
بي ارزش سوق داده شود. ايشان هم شرط مرا پذيرفتند و الحق 
والانصاف جز فعاليت راديويي هيچ فعاليت ديگري انجام 
ندادند و من هم تمام تلاشم را كردم كه براي اين بانوي 
فهميده و اهل معنا آهنگ مناسب و خوبي بسازم و به همين 
دليل آهنگ "امشب در سر شوري دارم "را ساختم كه شعرش را
هم آقاي كريم فكور سرودند. 
گفت و گو: سيروس جاهد]]>
</TEXT>
</DOC>
<DOC>
<DOCID>HAM2-801109-002</DOCID>
<DOCNO>HAM2-801109-002</DOCNO>
<ORIGINALFILE>/1380/801109/adabh.htm</ORIGINALFILE>
<ISSUE>29 jan 2002 سه شنبه 9بهمن 1380،، شماره 2635</ISSUE>
<DATE calender="Western">2002-01-29</DATE>
<DATE calender="Persian">1380/11/09</DATE>
<CAT xml:lang="fa">ادب و هنر</CAT>
